<?php
/**
 * @file Drupal's settings.php file
 *
 * This file was automatically generated by Aegir 7.x-3.172
 * on Sun, 28 Jul 2019 04:17:11 +0200.
 *
 * If it is still managed by Aegir, changes to this file may be
 * lost. If it is not managed by aegir, you should remove this header
 * to avoid further confusion.
 */


if (isset($_SERVER['db_name'])) {
  /**
   * The database credentials are stored in the Apache or Nginx vhost config
   * of the associated site with SetEnv (fastcgi_param in Nginx) parameters.
   * They are called here with $_SERVER environment variables to
   * prevent sensitive data from leaking to site administrators
   * with PHP access, that potentially might be of other sites in
   * Drupal's multisite set-up.
   * This is a security measure implemented by the Aegir project.
   */
  $databases['default']['default'] = array(
    'driver' => $_SERVER['db_type'],
    'database' => $_SERVER['db_name'],
    'username' => $_SERVER['db_user'],
    'password' => $_SERVER['db_passwd'],
    'host' => $_SERVER['db_host'],
    /* Drupal interprets $databases['db_port'] as a string, whereas Drush sees
     * it as an integer. To maintain consistency, we cast it to a string. This
     * should probably be fixed in Drush.
     */
    'port' => (string) $_SERVER['db_port'],
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_general_ci',
  );
  $db_url['default'] = $_SERVER['db_type'] . '://' . $_SERVER['db_user'] . ':' . $_SERVER['db_passwd'] . '@' . $_SERVER['db_host'] . ':' . $_SERVER['db_port'] . '/' . $_SERVER['db_name'];
}

  /**
   * Now that we used the credentials from the apache environment, we
   * don't need them anymore. Clear them from apache and the _SERVER
   * array, otherwise they show up in phpinfo() and other friendly
   * places.
   */
  if (function_exists('apache_setenv')) {
    apache_setenv('db_type', null);
    apache_setenv('db_user', null);
    apache_setenv('db_passwd', null);
    apache_setenv('db_host', null);
    apache_setenv('db_port', null);
    apache_setenv('db_name', null);
    // no idea why they are also in REDIRECT_foo, but they are
    apache_setenv('REDIRECT_db_type', null);
    apache_setenv('REDIRECT_db_user', null);
    apache_setenv('REDIRECT_db_passwd', null);
    apache_setenv('REDIRECT_db_host', null);
    apache_setenv('REDIRECT_db_port', null);
    apache_setenv('REDIRECT_db_name', null);
  }
  unset($_SERVER['db_type']);
  unset($_SERVER['db_user']);
  unset($_SERVER['db_passwd']);
  unset($_SERVER['db_host']);
  unset($_SERVER['db_port']);
  unset($_SERVER['db_name']);
  unset($_SERVER['REDIRECT_db_type']);
  unset($_SERVER['REDIRECT_db_user']);
  unset($_SERVER['REDIRECT_db_passwd']);
  unset($_SERVER['REDIRECT_db_host']);
  unset($_SERVER['REDIRECT_db_port']);
  unset($_SERVER['REDIRECT_db_name']);


  $profile = "standard";
  $install_profile = "standard";

  /**
  * PHP settings:
  *
  * To see what PHP settings are possible, including whether they can
  * be set at runtime (ie., when ini_set() occurs), read the PHP
  * documentation at http://www.php.net/manual/en/ini.php#ini.list
  * and take a look at the .htaccess file to see which non-runtime
  * settings are used there. Settings defined here should not be
  * duplicated there so as to avoid conflict issues.
  */
  ini_set('session.gc_probability', 1);
  ini_set('session.gc_divisor', 100);
  ini_set('session.gc_maxlifetime', 200000);
  ini_set('session.cookie_lifetime', 2000000);

  /**
  * Set the umask so that new directories created by Drupal have the correct permissions
  */
  umask(0002);

  $settings['install_profile'] = 'standard';
  $settings['file_public_path'] = 'sites/practice.ronaldpgarcia.com/files';
  $settings['file_private_path'] = 'sites/practice.ronaldpgarcia.com/private/files';
  $config['system.file']['path']['temporary'] = 'sites/practice.ronaldpgarcia.com/private/temp';
  $config_directories[CONFIG_SYNC_DIRECTORY] = 'sites/practice.ronaldpgarcia.com/private/config/sync';
  $settings['hash_salt'] = 'HtqOGY7PYynU--8rItrneCs_u5E4tI1eVDzr-mb8NCyYW3ZN5_c2pvSY57v9WSItiyuZMz2-NA';
  $settings['aegir_api'] = 3;
  $settings['allow_authorize_operations'] = FALSE;

  /**
   * Useless currently, because it is not used in Drupal 8 anyway.
   * Instead, Drupal 8 is trying to set the clean URLs mode on the fly,
   * depending on the request, so we should force this by redirecting
   * non-clean to clean URLs on the web server level - Nginx example:
   *
   *   rewrite ^/index.php/(.*)$ $scheme://$host/$1 permanent;
   *
   */
  $settings['clean_url'] = 1;


  /**
   * Load services definition file.
   */
  $settings['container_yamls'][] = __DIR__ . '/services.yml';

  /**
   * Trusted Host Settings support.
   */
  $settings['trusted_host_patterns'] = array(
    '^practice\.ronaldpgarcia\.com$',
    '^practice\.ronaldpgarcia\.loc$',
    '^localhost$',
    '^localhost\.*',
    '\.local$',
  );

# Extra configuration from modules:

  # Additional host wide configuration settings. Useful for safely specifying configuration settings.
  if (is_readable('/var/aegir/config/includes/global.inc')) {
    include('/var/aegir/config/includes/global.inc');
  }

  # Additional platform wide configuration settings.
  if (is_readable('/var/aegir/platforms/projectd8/sites/all/platform.settings.php')) {
    include('/var/aegir/platforms/projectd8/sites/all/platform.settings.php');
  }

  # Additional site configuration settings.
  if (is_readable('/var/aegir/platforms/projectd8/sites/practice.ronaldpgarcia.com/local.settings.php')) {
    include('/var/aegir/platforms/projectd8/sites/practice.ronaldpgarcia.com/local.settings.php');
  }
